{% set name = "audioop-lts" %}
{% set version = "0.2.1" %}
{% set build_number = 1 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/audioop_lts-{{ version }}.tar.gz
  sha256: e81268da0baa880431b68b1308ab7257eb33f356e57a5f9b1f915dfb13dd1387

build:
  {% if build_script == 'noop' %}
  number: {{ build_number | int * 2 + 1 }}
  script: bash {{ RECIPE_DIR }}/noop.sh
  noarch: python
  {% else %}
  number: {{ build_number | int * 2 }}
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  {% endif %}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    {% if build_script == 'noop' %}
    - python <3.13
    {% else %}
    - python >=3.13
    {% endif %}
    - setuptools
    - pip
  run:
    {% if build_script == 'noop' %}
    - python <3.13
    {% else %}
    - python >=3.13
    {% endif %}

test:
  imports:
    - audioop
  commands:
    - pip check
    # Verify that a basic audioop operation works as expected
    - python -c "import audioop; assert list(audioop.reverse(bytes([1,2,4,8]), 2)) == [4, 8, 1, 2]"
  requires:
    - python
    - pip

about:
  summary: LTS Port of Python audioop
  license: EPL-2.0
  license_file: LICENSE
  home: https://github.com/AbstractUmbra/audioop

extra:
  recipe-maintainers:
    - bmcfee
