{% set name = "audioop-lts" %}
{% set version = "0.2.1" %}
{% set python_min = "3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/audioop_lts-{{ version }}.tar.gz
  sha256: e81268da0baa880431b68b1308ab7257eb33f356e57a5f9b1f915dfb13dd1387

build:
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py < 313]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - audioop
  commands:
    - pip check
    # Verify that a basic audioop operation works as expected
    - python -c "import audioop; assert list(audioop.reverse(bytes([1,2,4,8]), 2)) == [4, 8, 1, 2]"
  requires:
    - python
    - pip

about:
  summary: LTS Port of Python audioop
  license: EPL-2.0
  license_file: LICENSE
  home: https://github.com/AbstractUmbra/audioop

extra:
  recipe-maintainers:
    - bmcfee
