schema_version: 1

context:
  name: audioop-lts
  version: 0.2.1
  python_min: 3.13

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/audioop_lts-${{ version }}.tar.gz
  sha256: e81268da0baa880431b68b1308ab7257eb33f356e57a5f9b1f915dfb13dd1387

build:
  number: 1
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - python 3.13.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - audioop
      python_version: ${{ python_min }}.*
  - requirements:
      run:
        - python ${{ python_min }}.*
        - pip
    script:
      - pip check

about:
  summary: LTS Port of Python audioop
  license: EPL-2.0
  license_file: LICENSE
  homepage: https://github.com/AbstractUmbra/audioop

extra:
  recipe-maintainers:
    - bmcfee
